# Generated by Django 3.0.8 on 2020-07-29 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name_plural': 'Entries'},
        ),
        migrations.AddField(
            model_name='entry',
            name='star_rating',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
