# Generated by Django 3.0.8 on 2020-07-29 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0002_auto_20200729_0116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='author',
            new_name='entry_author',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='date',
            new_name='entry_date',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='star_rating',
            new_name='entry_rating',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='text',
            new_name='entry_text',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='title',
            new_name='entry_title',
        ),
    ]
