# Generated by Django 3.0.8 on 2020-07-29 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0003_auto_20200729_0253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='entry_author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='entry_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='entry_rating',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='entry_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='entry_title',
            new_name='title',
        ),
    ]
